### ISSUE TITLE
Time for blind up/down

### ISSUE THREAD

**Issue by erokoder** [knstntn1/homebridge-mqtt-blinds#2]
Hello,
I have some question before use this plugin.
Where I can set time for up/down blinds?
Do you set time in configuration to sonoff device?
Also, are use orginal Sonoff firmware, or you flush some other?

Thanks for plugin and respons :D 

Best Regards,
Rade

**Comment by faltim** [comment]
You don't need a time for the plugin. I don't use any Sonoff firmware. I build up a blind by myself using a stepper motor and 3d printer. I wrote my own firmware. Because I use a stepper motor, the firmware knows the position of the blind at every time. My blinds are still work in progress. I will upload the firmware and some tutorials in a few month.

Inspirational examples:
http://www.instructables.com/id/Motorized-WiFi-IKEA-Roller-Blind/
https://www.thingiverse.com/thing:2392856

In your case the plugin will not work. You need a plugin with more logic.
